columns:
  - Booking_ID: category
  - no_of_adults: int
  - no_of_children: int
  - no_of_weekend_nights: int
  - no_of_week_nights: int
  - type_of_meal_plan: category
  - required_car_parking_space: int
  - room_type_reserved: category
  - lead_time: int
  - arrival_year:  int
  - arrival_month: int
  - arrival_date: int
  - market_segment_type: category
  - repeated_guest: int
  - no_of_previous_cancellations: int
  - no_of_previous_bookings_not_canceled: int
  - avg_price_per_room: int
  - no_of_special_requests: int
  - booking_status: category


numerical_columns:
  - no_of_adults
  - no_of_children
  - no_of_weekend_nights
  - no_of_week_nights
  - required_car_parking_space
  - lead_time
  - arrival_year
  - arrival_month
  - arrival_date
  - repeated_guest
  - no_of_previous_cancellations
  - no_of_previous_bookings_not_canceled
  - avg_price_per_room
  - no_of_special_requests


categorical_columns:
  - Booking_ID
  - type_of_meal_plan
  - room_type_reserved
  - market_segment_type
  - booking_status

drop_columns:
  - Booking_ID